name: CI/CD para API FastAPI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Cambiar por la versión de Python que estés utilizando

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Desplegar API
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000  # Cambiar por el comando que utilizas para ejecutar tu API
